#%RAML 1.0
---
title: Adapter REST API
baseUri: adapter-url/api
version: v1

types:
  GenericError:
    type: string

  PostMeasureReceivedBody:
    type: object
    properties:
      HostName:
        description: |
          Specify name of the Host from wich you want to fetch measurements
        type: string
        required: true

      DialNames:
        description: |
          Specify names of dials that are going to be measured
        type: string[]
        required: true

  PostMeasureSentBody:
    type: object
    properties:
      HostName:
        description: |
          Name of the Name from which the measurement data was fetched
        type: string
        required: true

      Measures:
        description: |
          List of measures
        type: Measure[]
        required: true

  Measure:
    type: object
    properties:
      DialName:
        description: |
          Name of the dial
        type: string
        required: true
      Value:
        description: |
          Value that was measured
        type: number
        required: true

  Host:
    type: object
    properties:
      HostName:
        description: |
          Name of the Host
        type: string
        required: true
  Dial:
    type: object
    properties:
      Name:
        description: |
          Name of the Dial
        type: string
        required: true
      Unit:
        description: |
          Unit of measurement
        type: string
        required: true
      Threshold:
        description: |
          Threshold above which runs are counted
        type: integer
        required: true
      RunCount:
        description: |
          Number of measurement values above threshold that are retrieved in a row for incident to occur
        type: integer
        required: true


/identifier:
  get:
    description: Retrieve identifier that describes what server cluster the adapter is attached to
    body:
      text/plain:
        example: |
          Generic-cluster-adapter

/hosts:
  get:
    description: Retrieve list of hosts supported by the adapter
    responses:
      200:
        body:
          application/json:
            type: Host[]
            example: |
              [
                {
                  "HostName": "host1"
                },
                {
                  "HostName": "host2"
                },
                {
                  "HostName": "host3"
                },
                {
                  "HostName": "host4"
                }
              ]

  # /{host_name}:
  #   get:

/dials:
  get:
    description: Retrieve list of dials supported by the adapter
    responses:
      200:
        body:
          application/json:
            type: Dial[]
            example: |
              [
                {
                    "Name": "Proc_All_%",
                    "Unit": "%",
                    "Threshold": 80,
                    "RunCount": 5 
                },
                {
                    "Name": "Mem_%",
                    "Unit": "%",
                    "Threshold": 75,
                    "RunCount": 6 
                },
                {
                    "Name": "Swap_Kb",
                    "Unit": "Kb",
                    "Threshold": 3000000,
                    "RunCount": 8 
                }
              ]

/measure:
  post:
    description: |
      Used to get measurement of a specified dials on a specified host
    body:
      application/json:
        type: PostMeasureReceivedBody
        example: |
          {
            "HostName": "host4",
            "DialNames": [
              "Processor_%",
              "Memory_%"
            ]
          }
    responses:
      200:
        body:
          application/json:
            type: PostMeasureSentBody
            example: |
              {
                "HostName": "host4",
                "Measures": [
                  {
                    "DialName": "Processor_%",
                    "Value": 110.1287328
                  },
                  {
                    "DialName": "Memory_%",
                    "Value": 78.398273
                  }
                ]
              }
      400:
        body:
          description: |
            Returns descriptive error string
          text/plain:
            type: GenericError
            example: |
              "Some error occured"