#%RAML 1.0
---
title: Worker REST API
baseUri: worker-url/api
version: v1

types:
  GenericError:
    type: string

  PostCollectStartBody:
    type: object
    properties:
      HostName:
        description: |
          Specify name of the host from wich you want to fetch measurement data. HostName has to be in adapter's hosts list
        type: string
        required: true

      AdapterIdentifier:
        description: |
          Identifier of an adapter. Used as a field in incident reports  
        type: string
        required: true

      Dials:
        description: |
          Specify the list of dials from which data will be measured. All dials have to be in adapter's dial list
        type: Dial[]
        required: true

  PostCollectDataBody:
    type: object
    properties:
      SessionID:
        description: |
          Specify UUID of a session that is collected by requesting /collect/start
        type: string
        required: true

      AdapterURL:
        description: |
          Specify the URL of an adapter from which the data will be collected
        type: string
        required: true

  Dial:
    type: object
    properties:
      Name:
        description: |
          Name of the Dial
        type: string
        required: true
      
      Threshold:
        description: |
          Threshold value above which run counter is incremented
        type: string
        required: true

      Unit:
        description: |
          Unit of measurement
        type: string
        required: true
      
      RunCount:
        description: |
          Count of occurences of value being above threshold to be concidered an incident
        type: string
        required: true
  
  Incident:
    type: object
    properties:
      HostName:
        description: |
          Name of the host
        type: string
        required: true

      AdapterIdentifier:
        description: |
          Identifier of an adapter
        type: string
        required: true

      DateTime:
        description: |
          Time and date of incident occurance
        type: string
        required: true

      Dial:
        description: |
          Information about dial
        type: Dial
        required: true



/identifier:
  get:
    description: Retrieve identifier that describes version and type of a worker
    body:
      text/plain:
        example: |
          Generic-worker

/incidents:
  get:
    responses:
      200:
        description: |
          Retreive list of incidents
        body:
          application/json:
            type: Incident[]
            example: |
              [
                {
                  "HostName": "host1",
                  "AdapterIdentifier": "Adapter-Generic-Cluster",
                  "DateTime": "2024-04-24T16:51:40.657204+03:00",
                  "Dial": {
                    "Name": "Proc_All_%",
                    "Unit": "%",
                    "Threshold": 65.3,
                    "RunCount": 4
                  }
                },
                {
                  "HostName": "host1",
                  "AdapterIdentifier": "Adapter-Generic-Cluster",
                  "DateTime": "2024-04-24T16:51:40.77794+03:00",
                  "Dial": {
                    "Name": "Proc_All_%",
                    "Unit": "%",
                    "Threshold": 65.3,
                    "RunCount": 4
                  }
                },
                {
                  "HostName": "host1",
                  "AdapterIdentifier": "Adapter-Generic-Cluster",
                  "DateTime": "2024-04-24T16:51:41.291331+03:00",
                  "Dial": {
                    "Name": "Proc_All_%",
                    "Unit": "%",
                    "Threshold": 65.3,
                    "RunCount": 4
                  }
                }
              ]

/collect:
  /start:
    post:
      description: |
        Starts a new session for processing data retreived from adapters.
        Calling /collect/data with token of the session will make worker
        request data from adapter with "query parameters" specifid at this 
        initialization step
      body:
        application/json:
          type: PostCollectStartBody
          example: |
            {
              "HostName": "host123",
              "AdapterIdentifier": "Adapter-Generic-Cluster",
              "Dials": [
                {
                  "Name": "Processor_%",
                  "Threshold": 65.3,
                  "Unit": "%",
                  "RunCount": 12
                },
                {
                  "Name": "Memory_%",
                  "Threshold": 89.3,
                  "Unit": "%",
                  "RunCount": 4
                }
              ]
            }
      responses:
        200:
          description: |
              Returns session token
          body:
            text/plain:
              type: string
              example: |
                "cd920844-0fac-44e1-b39c-08234502c79b"
        400:
          description: |
            Returns descriptive error string
          body:
            text/plain:
              type: GenericError
              example: |
                "Some error occured"
  
  /data:
    post:
      description: |
        Instructs worker to retrieve and process data from post /api/measure url of an adapter
      body:
        application/json:
          type: PostCollectDataBody
          example: |
            {
              "SessionID": "cd920844-0fac-44e1-b39c-08234502c79b",
              "AdapterURL": "http://adapter-url/api/measure"
            }
      responses:
        200:
          description: |
            Empty body
        400:
          description: |
            Returns descriptive error string
          body:
            text/plain:
              type: string
              example: |
                "Some error occured"
  /stop:
    post:
